[package]
name = "error_handling"
version = "0.1.0"
authors = ["byungil <sysroad@gmail.com>"]
edition = "2018"

[profile.release]
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
